Exercises
Do your work for this exercise in a jupyter notebook named hypothesis_testing.ipynb.

For each of the following questions, formulate a null and alternative hypothesis (be as specific as you can be), then give an example of what a true positive, true negative, type I and type II errors would look like. Note that some of the questions are intentionally phrased in a vague way. It is your job to reword these as more precise questions that could be tested.

- do I need to reword the question?
- what are the variables?
- what type are the variables?
- formulate null hypothesis
- formulate alt hypothesis
- example of True Positive
- Example of True Negative
- example of Type 1 error (False Positive)
- example of Type 2 error (False Negative)
- what type of tests should I run?

### 1. Has the network latency gone up since we switched internet service providers?
##### do I need to reword the question?
- Has there been a statistically significant increase in network latency since we switched ISPs?
##### what are the variables?
- old_isp
- new_isp
- network_latency
##### what type are the variables?
- old_isp = categorical/discrete
- new_isp = categorical/discrete
- network_latency = numerical/continuous
##### formulate null hypothesis
- H0 = no stat significant change in network latency since we switched ISPs
##### formulate alt hypothesis
- Ha = there has been a significant increase in network latency since we switched ISPs
##### formulate alt hypothesis
- Ha = there has been a significant change in network latency since we switched ISPs
##### example of True Positive
- H0 = False
- There is a significant change in network latency after switching
##### Example of True Negative
- H0 = True
- There is no significant change in network latency after switching
##### example of Type 1 error (False Positive)
- H0 = True, but we get data that says H0 = False
- we say there is significant change, when in reality there is not
##### example of Type 2 error (False Negative)
- H0 = False, but we get data that says H0 = True
- we say there is no significant change, when in reality there is
##### what type of test(s) would I run?

### 2. Is the website redesign any good?
##### do I need to reword the question?
- how do we quantify changes to website redesign?
- Is there a statistically significant increase in time spent on website after redesign?
##### what are the variables?
- old_website = categorical / discrete
- new_website = categorical / discrete
- time_onsite = numerical / continuous
##### what type are the variables?
##### formulate null hypothesis
- H0 = there is no significant change in time on_site after website redesign
##### formulate alt hypothesis
- Ha = there is a significant increase in time on_site after website redesign
##### example of True Positive
- H0 = False
- There is a significant increase in time_onsite
##### Example of True Negative
- H0 = True
- There is no significant change in time_onsite after redesign
##### example of Type 1 error (False Positive)
- H0 = True, but our data says H0 = False
- There is no significant change in time_onsite, but our data suggests that there is significant change
##### example of Type 2 error (False Negative)
- H0 = False, but our data says H0 = True
- There is a significant change in time_onsite, but our data suggests no significant change
##### what type of test(s) would I run?

### 3. Is our television ad driving more sales?
##### do I need to reword the question?
- Has our tv ad led to a statistically significant increase in sales revenue? (measuring in avg weekly revenue?)
##### what are the variables?
- pre_ad
- post_ad
- weekly_ad_rev
##### what type are the variables?
- pre_ad = categorical / discrete
- post_ad = categorical / discrete
- weekly_ad_rev = numerical / continuous
##### formulate null hypothesis
- H0 = there is no significant change in weekly revenue after new tv ad
##### formulate alt hypothesis
- H1 = there has been a statistically significant increase in weekly revenue after new sales ad
- H2 = there has been a statistically significant decrease in weekly revenue after new tv ad
##### example of True Positive
- H0 = False
- There is a statistically significant change in weekly revenue after the new tv ad
##### Example of True Negative
- H0 = True
- There is no statistically significant change in weekly revenue after the new tv ad
##### example of Type 1 error (False Positive)
- H0 = True, but our data suggests H0 = False
- There is no change, but our data suggests that there is
##### example of Type 2 error (False Negative)
- H0 = False, but our data suggests H0 = True
- There is significant change, but our data suggests no change
##### what type of test(s) would I run?

# T-Test Time

Exercises
Continue working in your hypothesis_testing notebook.

In [1]:
import numpy as np
import seaborn as sns
import scipy.stats as stats
import pandas as pd
import matplotlib.pyplot as plt
from pydataset import data
from datetime import date

1. Ace Realty wants to determine whether the average time it takes to sell homes is different for its two offices. A sample of 40 sales from office #1 revealed a mean of 90 days and a standard deviation of 15 days. A sample of 50 sales from office #2 revealed a mean of 100 days and a standard deviation of 20 days. Use a .05 level of significance.

- do I need to reword the question?
    - Is there a statistically significent difference in sales time between office1 and office2?
- what are the variables?
- what type are the variables?
    - office1 = categorical / discrete
    - office2 = categorical / discrete
    - time_to_sell = numerical / continuous
- formulate null hypothesis
    - $H_{0}$: There is no difference in sales time between office1 and office2.
- formulate alt hypothesis
    - $H_{a}$: There is a statistically significant difference in sales time between office1 and office2.
- example of True Positive
    - $H_{0}$: False, so we reject $H_{0}$, There is a statistically significant difference in sales time between office1 and office2, and our data backs that up.
- Example of True Negative
    - $H_{0}$: True, so we accept $H_{0}$, There is no difference in sales time, and our data backs this up.
- example of Type 1 error (False Positive)
    - $H_{0}$: True, (There is no difference) but our data suggests it is False (We see a difference), so we incorrectly reject $H_{0}$
- example of Type 2 error (False Negative)
    - $H_{0}$: False, (There is a differnce) but our data suggests it is True (There is no difference), so we incorrectly accept the $H_{0}$
- what type of tests should I run?

1. Ace Realty wants to determine whether the average time it takes to sell homes is different for its two offices. A sample of 40 sales from office #1 revealed a mean of 90 days and a standard deviation of 15 days. A sample of 50 sales from office #2 revealed a mean of 100 days and a standard deviation of 20 days. Use a .05 level of significance.

In [2]:
# office1 variables
mean1 = 90
std1 = 15
ct1 = 40
# office2 variables
mean2 = 100
std2 = 20
ct2 = 50
# others
alpha = 0.05
# check variance
office1 = stats.norm(mean1, std1)
office2 = stats.norm(mean2, std2)
office1.var(), office2.var()


(225.0, 400.0)

In [3]:
t, p = stats.ttest_ind_from_stats(mean1, std1, ct1, mean2, std2, ct2, equal_var = False)

t, p, alpha

(-2.7091418459143854, 0.00811206270346016, 0.05)

In [ ]:
# What does it mean???
# Office1 sells on average 2.7 days faster (less) than office2
# the p value < alpha, so we know this is not by chance

# This is an example of True Positive


$H_{0}$: False (There is a difference), and our data backs up the fact that there is a difference in sales time

2. Load the mpg dataset and use it to answer the following questions:

In [4]:
mpg_df = data('mpg')
mpg_df.head()                 

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [5]:
# Creating Column for average mileage
mpg_df["average_mileage"] = (mpg_df.hwy + mpg_df.cty) / 2

In [6]:
df_1999 = mpg_df[mpg_df['year'] == 1999]
df_1999


manufacturer                   model  displ  year  cyl       trans drv  \
1           audi                      a4    1.8  1999    4    auto(l5)   f   
2           audi                      a4    1.8  1999    4  manual(m5)   f   
5           audi                      a4    2.8  1999    6    auto(l5)   f   
6           audi                      a4    2.8  1999    6  manual(m5)   f   
8           audi              a4 quattro    1.8  1999    4  manual(m5)   4   
9           audi              a4 quattro    1.8  1999    4    auto(l5)   4   
12          audi              a4 quattro    2.8  1999    6    auto(l5)   4   
13          audi              a4 quattro    2.8  1999    6  manual(m5)   4   
16          audi              a6 quattro    2.8  1999    6    auto(l5)   4   
22     chevrolet      c1500 suburban 2wd    5.7  1999    8    auto(l4)   r   
24     chevrolet                corvette    5.7  1999    8  manual(m6)   r   
25     chevrolet                corvette    5.7  1999    8    auto(l4)   r   
31     chevrolet         k1500 tahoe 4wd    5.7  1999    8    auto(l4)   4   
32     chevrolet         k1500 tahoe 4wd    6.5  1999    8    auto(l4)   4   
33     chevrolet                  malibu    2.4  1999    4    auto(l4)   f   
35     chevrolet                  malibu    3.1  1999    6    auto(l4)   f   
38         dodge             caravan 2wd    2.4  1999    4    auto(l3)   f   
39         dodge             caravan 2wd    3.0  1999    6    auto(l4)   f   
40         dodge             caravan 2wd    3.3  1999    6    auto(l4)   f   
41         dodge             caravan 2wd    3.3  1999    6    auto(l4)   f   
45         dodge             caravan 2wd    3.8  1999    6    auto(l4)   f   
46         dodge             caravan 2wd    3.8  1999    6    auto(l4)   f   
51         dodge       dakota pickup 4wd    3.9  1999    6    auto(l4)   4   
52         dodge       dakota pickup 4wd    3.9  1999    6  manual(m5)   4   
56         dodge       dakota pickup 4wd    5.2  1999    8  manual(m5)   4   
57         dodge       dakota pickup 4wd    5.2  1999    8    auto(l4)   4   
58         dodge             durango 4wd    3.9  1999    6    auto(l4)   4   
62         dodge             durango 4wd    5.2  1999    8    auto(l4)   4   
64         dodge             durango 4wd    5.9  1999    8    auto(l4)   4   
71         dodge     ram 1500 pickup 4wd    5.2  1999    8    auto(l4)   4   
72         dodge     ram 1500 pickup 4wd    5.2  1999    8  manual(m5)   4   
74         dodge     ram 1500 pickup 4wd    5.9  1999    8    auto(l4)   4   
75          ford          expedition 2wd    4.6  1999    8    auto(l4)   r   
76          ford          expedition 2wd    5.4  1999    8    auto(l4)   r   
78          ford            explorer 4wd    4.0  1999    6    auto(l5)   4   
79          ford            explorer 4wd    4.0  1999    6  manual(m5)   4   
80          ford            explorer 4wd    4.0  1999    6    auto(l5)   4   
83          ford            explorer 4wd    5.0  1999    8    auto(l4)   4   
84          ford         f150 pickup 4wd    4.2  1999    6    auto(l4)   4   
85          ford         f150 pickup 4wd    4.2  1999    6  manual(m5)   4   
86          ford         f150 pickup 4wd    4.6  1999    8  manual(m5)   4   
87          ford         f150 pickup 4wd    4.6  1999    8    auto(l4)   4   
89          ford         f150 pickup 4wd    5.4  1999    8    auto(l4)   4   
91          ford                 mustang    3.8  1999    6  manual(m5)   r   
92          ford                 mustang    3.8  1999    6    auto(l4)   r   
95          ford                 mustang    4.6  1999    8    auto(l4)   r   
96          ford                 mustang    4.6  1999    8  manual(m5)   r   
100        honda                   civic    1.6  1999    4  manual(m5)   f   
101        honda                   civic    1.6  1999    4    auto(l4)   f   
102        honda                   civic    1.6  1999    4  manual(m5)   f   
103        honda          

In [7]:
cars_1999 = mpg_df['average_mileage'][mpg_df['year']==1999]
cars_1999.head()

1    23.5
2    25.0
5    21.0
6    22.0
8    22.0
Name: average_mileage, dtype: float64

In [8]:
std_1999 = mpg_df['average_mileage'][mpg_df['year']==1999].std()
std_1999

5.207936766511732

In [9]:
cars_2008 = mpg_df['average_mileage'][mpg_df['year']==2008]
cars_2008.head()

3     25.5
4     25.5
7     22.5
10    24.0
11    23.0
Name: average_mileage, dtype: float64

In [10]:
std_2008 = mpg_df['average_mileage'][mpg_df['year']==2008].std()
std_2008

4.90891842528482

In [11]:
t, p = stats.ttest_ind(cars_2008, cars_1999, equal_var = False)
t, p , alpha

(-0.21960177245940962, 0.8263750772060638, 0.05)

2a. Is there a difference in fuel-efficiency in cars from 2008 vs 1999?

- do I need to reword the question?
    - Has there been a statistically significant increase in fuel-efficiency in cars from 1999 to 2008?
- what are the variables?
- what type are the variables?
    - cars1999 = categorical / discrete
    - cars2008 = categorical / discrete
    - mpg = numerical / continuous
- formulate null hypothesis
    - $H_{0}$: There has been no change in fuel efficiency from 1999 to 2008
- formulate alt hypothesis
    - $H{0}$: There has been a statistically significant increase in fuel-efficiency in cars from 1999 to 2008
- example of True Positive
    - $H{0}$: False, (There has been a change,) we reject the $H{0}$, and our data backs that up
- Example of True Negative
    - $H{0}$: True, (There has been no change,) we accept the $H{0}$, and our data backs that up
- example of Type 1 error (False Positive)
    - $H{0}$: True, (There has been no change,) we incorrectly reject the $H{0}$,  because our data suggests change
- example of Type 2 error (False Negative)
    - $H{0}$: False, (There has been a change,) we incorrectly accept the $H{0}$, because our data suggests no change
- what type of tests should I run?

In [12]:
types_1999 = mpg_df[mpg_df['year']==1999]
types_1999


manufacturer                   model  displ  year  cyl       trans drv  \
1           audi                      a4    1.8  1999    4    auto(l5)   f   
2           audi                      a4    1.8  1999    4  manual(m5)   f   
5           audi                      a4    2.8  1999    6    auto(l5)   f   
6           audi                      a4    2.8  1999    6  manual(m5)   f   
8           audi              a4 quattro    1.8  1999    4  manual(m5)   4   
9           audi              a4 quattro    1.8  1999    4    auto(l5)   4   
12          audi              a4 quattro    2.8  1999    6    auto(l5)   4   
13          audi              a4 quattro    2.8  1999    6  manual(m5)   4   
16          audi              a6 quattro    2.8  1999    6    auto(l5)   4   
22     chevrolet      c1500 suburban 2wd    5.7  1999    8    auto(l4)   r   
24     chevrolet                corvette    5.7  1999    8  manual(m6)   r   
25     chevrolet                corvette    5.7  1999    8    auto(l4)   r   
31     chevrolet         k1500 tahoe 4wd    5.7  1999    8    auto(l4)   4   
32     chevrolet         k1500 tahoe 4wd    6.5  1999    8    auto(l4)   4   
33     chevrolet                  malibu    2.4  1999    4    auto(l4)   f   
35     chevrolet                  malibu    3.1  1999    6    auto(l4)   f   
38         dodge             caravan 2wd    2.4  1999    4    auto(l3)   f   
39         dodge             caravan 2wd    3.0  1999    6    auto(l4)   f   
40         dodge             caravan 2wd    3.3  1999    6    auto(l4)   f   
41         dodge             caravan 2wd    3.3  1999    6    auto(l4)   f   
45         dodge             caravan 2wd    3.8  1999    6    auto(l4)   f   
46         dodge             caravan 2wd    3.8  1999    6    auto(l4)   f   
51         dodge       dakota pickup 4wd    3.9  1999    6    auto(l4)   4   
52         dodge       dakota pickup 4wd    3.9  1999    6  manual(m5)   4   
56         dodge       dakota pickup 4wd    5.2  1999    8  manual(m5)   4   
57         dodge       dakota pickup 4wd    5.2  1999    8    auto(l4)   4   
58         dodge             durango 4wd    3.9  1999    6    auto(l4)   4   
62         dodge             durango 4wd    5.2  1999    8    auto(l4)   4   
64         dodge             durango 4wd    5.9  1999    8    auto(l4)   4   
71         dodge     ram 1500 pickup 4wd    5.2  1999    8    auto(l4)   4   
72         dodge     ram 1500 pickup 4wd    5.2  1999    8  manual(m5)   4   
74         dodge     ram 1500 pickup 4wd    5.9  1999    8    auto(l4)   4   
75          ford          expedition 2wd    4.6  1999    8    auto(l4)   r   
76          ford          expedition 2wd    5.4  1999    8    auto(l4)   r   
78          ford            explorer 4wd    4.0  1999    6    auto(l5)   4   
79          ford            explorer 4wd    4.0  1999    6  manual(m5)   4   
80          ford            explorer 4wd    4.0  1999    6    auto(l5)   4   
83          ford            explorer 4wd    5.0  1999    8    auto(l4)   4   
84          ford         f150 pickup 4wd    4.2  1999    6    auto(l4)   4   
85          ford         f150 pickup 4wd    4.2  1999    6  manual(m5)   4   
86          ford         f150 pickup 4wd    4.6  1999    8  manual(m5)   4   
87          ford         f150 pickup 4wd    4.6  1999    8    auto(l4)   4   
89          ford         f150 pickup 4wd    5.4  1999    8    auto(l4)   4   
91          ford                 mustang    3.8  1999    6  manual(m5)   r   
92          ford                 mustang    3.8  1999    6    auto(l4)   r   
95          ford                 mustang    4.6  1999    8    auto(l4)   r   
96          ford                 mustang    4.6  1999    8  manual(m5)   r   
100        honda                   civic    1.6  1999    4  manual(m5)   f   
101        honda                   civic    1.6  1999    4    auto(l4)   f   
102        honda                   civic    1.6  1999    4  manual(m5)   f   
103        honda          

In [ ]:
# what does it all mean?
# inconclusive test results
# very high p-value
# why??
#     different classes of cars being compared?
#     different fuel types?
#     need to dive into the charts, to determine what we are actually comparing
#     this is a biased study, and needs to be reworked

2b. Are compact cars more fuel-efficient than the average car?

- do I need to reword the question?
- what are the variables?
- what type are the variables?
- formulate null hypothesis
- formulate alt hypothesis
- example of True Positive
- Example of True Negative
- example of Type 1 error (False Positive)
- example of Type 2 error (False Negative)
- what type of tests should I run?
    -1 sample ttest, 1 tail

In [13]:
compact = mpg_df['average_mileage'][mpg_df['class']=='compact']
compact.head()

1    23.5
2    25.0
3    25.5
4    25.5
5    21.0
Name: average_mileage, dtype: float64

In [14]:
all_mpg = mpg_df['average_mileage'].mean()
all_mpg

20.14957264957265

In [15]:
t, p = stats.ttest_1samp(compact, all_mpg)
t, p/2, alpha

(7.896888573132535, 2.0992818971585668e-10, 0.05)

In [16]:
if (p/2 < alpha) & (t > 0):
    print("We reject the null hypothesis")
else:
    print("We fail to reject the null hypothesis")

We reject the null hypothesis


In [ ]:
# what does it mean???
# this is a true positive
# 

2c. Do manual cars get better gas mileage than automatic cars?

- do I need to reword the question?
- what are the variables?
- what type are the variables?
- formulate null hypothesis
- formulate alt hypothesis
- example of True Positive
- Example of True Negative
- example of Type 1 error (False Positive)
- example of Type 2 error (False Negative)
- what type of tests should I run?
    - 2 sample, 1 tail

In [17]:
manuals = mpg_df[mpg_df.trans.str.contains('manual')]
manuals.head()

manufacturer       model  displ  year  cyl       trans drv  cty  hwy fl  \
2          audi          a4    1.8  1999    4  manual(m5)   f   21   29  p   
3          audi          a4    2.0  2008    4  manual(m6)   f   20   31  p   
6          audi          a4    2.8  1999    6  manual(m5)   f   18   26  p   
8          audi  a4 quattro    1.8  1999    4  manual(m5)   4   18   26  p   
10         audi  a4 quattro    2.0  2008    4  manual(m6)   4   20   28  p   

      class  average_mileage  
2   compact             25.0  
3   compact             25.5  
6   compact             22.0  
8   compact             22.0  
10  compact             24.0

In [18]:
manuals_mpg = manuals['average_mileage']
manuals_mpg.head()

2     25.0
3     25.5
6     22.0
8     22.0
10    24.0
Name: average_mileage, dtype: float64

In [19]:
automatics = mpg_df[mpg_df.trans.str.contains('auto')]
automatics.head()

manufacturer       model  displ  year  cyl     trans drv  cty  hwy fl  \
1         audi          a4    1.8  1999    4  auto(l5)   f   18   29  p   
4         audi          a4    2.0  2008    4  auto(av)   f   21   30  p   
5         audi          a4    2.8  1999    6  auto(l5)   f   16   26  p   
7         audi          a4    3.1  2008    6  auto(av)   f   18   27  p   
9         audi  a4 quattro    1.8  1999    4  auto(l5)   4   16   25  p   

     class  average_mileage  
1  compact             23.5  
4  compact             25.5  
5  compact             21.0  
7  compact             22.5  
9  compact             20.5

In [20]:
automatics_mpg = automatics['average_mileage']
automatics_mpg.head()

1    23.5
4    25.5
5    21.0
7    22.5
9    20.5
Name: average_mileage, dtype: float64

In [21]:
t, p = stats.ttest_ind(manuals_mpg, automatics_mpg, equal_var = False)

t, p/2, alpha

(4.443514012903071, 8.976124499958965e-06, 0.05)

In [22]:
if (p/2 < alpha) & (t > 0):
    print("We reject the null hypothesis")
else:
    print("We fail to reject the null hypothesis")

We reject the null hypothesis


Exercises
Continue working in your hypothesis_testing notebook.

1. Use the telco_churn data. Does tenure correlate with monthly charges? Total charges? What happens if you control for phone and internet service?

In [23]:
# load our data
telco_df = pd.read_csv('Cust_Churn_Telco.csv')
telco_df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [24]:
telco_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


- do I need to reword the question?
    - Q1: Does tenure correlate with monthly charges?
    - Q2: Does tenure correlate with total charges?
    - Q3: What if we control for phone and internet service?
- what are the variables?
    - tenure
    - charges (monthly / total)
- what type are the variables?
    - tenure: numerical / continuous
    - charges: numerical / continuous
- formulate null hypothesis
    - $H_{0}$: There is no correlation between tenure and charges
- formulate alt hypothesis
    - $H_{0}$: There is a correlation between tenure and charges
- example of True Positive
    - $H_{0}$: False, our data backs that up, and we Reject the $H_{0}$
- Example of True Negative
- example of Type 1 error (False Positive)
- example of Type 2 error (False Negative)
- what type of tests should I run?

In [25]:
telco_df['TotalCharges'] = pd.to_numeric(telco_df['TotalCharges'], errors='coerce')
telco_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [26]:
telco_df = telco_df.dropna()
telco_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7032 non-null   object 
 1   gender            7032 non-null   object 
 2   SeniorCitizen     7032 non-null   int64  
 3   Partner           7032 non-null   object 
 4   Dependents        7032 non-null   object 
 5   tenure            7032 non-null   int64  
 6   PhoneService      7032 non-null   object 
 7   MultipleLines     7032 non-null   object 
 8   InternetService   7032 non-null   object 
 9   OnlineSecurity    7032 non-null   object 
 10  OnlineBackup      7032 non-null   object 
 11  DeviceProtection  7032 non-null   object 
 12  TechSupport       7032 non-null   object 
 13  StreamingTV       7032 non-null   object 
 14  StreamingMovies   7032 non-null   object 
 15  Contract          7032 non-null   object 
 16  PaperlessBilling  7032 non-null   object 


In [27]:
x_ten = telco_df['tenure']
y_monthly = telco_df['MonthlyCharges']
alpha = 0.05

In [28]:
r, p = stats.pearsonr(x_ten, y_monthly)
r, p

(0.2468617666408957, 3.9898213232510553e-98)

In [ ]:
# there is a weak positive correlation between tenure and monthly charges

In [29]:
x_ten = telco_df['tenure']
y_total = telco_df['TotalCharges']
alpha = 0.05

In [30]:
r, p = stats.pearsonr(x_ten, y_total)
r, p

(0.8258804609332093, 0.0)

In [ ]:
# this shows a relatively strong positive correlation between tenure and total charges
# did we mess up?? - p value = 0, not close to zero

In [31]:
# now let's look at adding some controls...
x_phone = telco_df['tenure'][telco_df['PhoneService']== 'Yes']
x_phone.head()

1    34
2     2
4     2
5     8
6    22
Name: tenure, dtype: int64

In [32]:
y_monthly = telco_df['MonthlyCharges'][telco_df['PhoneService']=='Yes']
y_monthly.head()

1    56.95
2    53.85
4    70.70
5    99.65
6    89.10
Name: MonthlyCharges, dtype: float64

In [33]:
y_total = telco_df['TotalCharges'][telco_df['PhoneService']=='Yes']
y_total.head()

1    1889.50
2     108.15
4     151.65
5     820.50
6    1949.40
Name: TotalCharges, dtype: float64

In [34]:
# phone service vs monthly

r, p = stats.pearsonr(x_phone, y_monthly)
r, p

(0.24419396575193372, 6.828016037598485e-87)

In [35]:
# phone service vs total charges

r, p = stats.pearsonr(x_phone, y_total)
r, p

(0.8298393210699477, 0.0)

In [36]:
x_depend = telco_df['tenure'][telco_df['Dependents']=='Yes']

In [37]:
y_dep_month = telco_df['MonthlyCharges'][telco_df['Dependents']=='Yes']

In [38]:
y_dep_total = telco_df['TotalCharges'][telco_df['Dependents']=='Yes']

In [39]:
r, p = stats.pearsonr(x_depend, y_dep_month)
r, p

(0.27683312413496897, 3.087829757170462e-38)

In [40]:
r, p = stats.pearsonr(x_depend, y_dep_total)
r, p

(0.7717345899465285, 0.0)

2. Use the employees database
    - Is there a relationship between how long an employee has been with the company and their salary?

In [ ]:
# what table(s) will I need?
# 

In [27]:
from env import host, user, password
url = f'mysql+pymysql://{user}:{password}@{host}/employees'

In [28]:
def get_db_url(db, user=user, host=host, password=password):
    return f'mysql+pymysql://{user}:{password}@{host}/{db}'

In [29]:
url = get_db_url('employees')

In [30]:
sql_query1 = 'SELECT * FROM employees'

In [31]:
def get_employees_data(db):
    return pd.read_sql(sql_query, get_db_url(db))

In [32]:
get_employees_data('employees')

emp_no  birth_date first_name last_name gender   hire_date
0        10001  1953-09-02     Georgi   Facello      M  1986-06-26
1        10002  1964-06-02    Bezalel    Simmel      F  1985-11-21
2        10003  1959-12-03      Parto   Bamford      M  1986-08-28
3        10004  1954-05-01  Chirstian   Koblick      M  1986-12-01
4        10005  1955-01-21    Kyoichi  Maliniak      M  1989-09-12
...        ...         ...        ...       ...    ...         ...
300019  499995  1958-09-24     Dekang  Lichtner      F  1993-01-12
300020  499996  1953-03-07       Zito      Baaz      M  1990-09-27
300021  499997  1961-08-03    Berhard    Lenart      M  1986-04-21
300022  499998  1956-09-05   Patricia   Breugel      M  1993-10-13
300023  499999  1958-05-01     Sachin   Tsukuda      M  1997-11-30

[300024 rows x 6 columns]

In [33]:
sql_query1 = 'SELECT * FROM employees'
sql_query2 = 'SELECT * FROM salaries'
sql_query3 = 'SELECT * FROM titles'

In [34]:
# get the 3 tables I need
employees_df = pd.read_sql(sql_query1, url)
salaries_df = pd.read_sql(sql_query2, url)
titles_df = pd.read_sql(sql_query3, url)


In [12]:
# aggregate titles by emp_no

In [39]:
sql_query4 = '''SELECT employees.*, salaries.salary, titles.title FROM employees as all
JOIN titles ON employees.emp_no = titles.emp_no
JOIN salaries ON employees.emp_no = salaries.emp_no;'''

In [40]:
all_df = pd.read_sql(sql_query4, url)

ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'all\nJOIN titles ON employees.emp_no = titles.emp_no\nJOIN salaries ON employees.e' at line 1")
[SQL: SELECT employees.*, salaries.salary, titles.title FROM employees as all
JOIN titles ON employees.emp_no = titles.emp_no
JOIN salaries ON employees.emp_no = salaries.emp_no;]
(Background on this error at: http://sqlalche.me/e/13/f405)

 - Is there a relationship between how long an employee has been with the company and their salary?

In [ ]:
# we need to create a new column of 'tenure'
# if current date = 9999, then we first need to convert to today

In [13]:
# bring in the titles df
titles_df = pd.read_sql('SELECT * FROM titles', url)

    - Is there a relationship between how long an employee has been with the company and the number of titles they have had?

In [15]:
sql_query = 'SELECT * FROM titles'

3. Use the sleepstudy data. Is there a relationship between days and reaction time?

### Notes from Review...

1. Use the following contingency table to help answer the question of whether using a macbook and being a codeup student are independent of each other.

In [14]:
codeup_student = pd.Series([49,1])
not_codeup_student = pd.Series([20,30])

df = pd.DataFrame({'Codeup Student': codeup_student,
                  'Not Codeup Student': not_codeup_student,
                  })
df = df.rename(index={0:'Uses a Macbook', 1: "Doesn't Use A Macbook"})
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Uses a Macbook to Doesn't Use A Macbook
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Codeup Student      2 non-null      int64
 1   Not Codeup Student  2 non-null      int64
dtypes: int64(2)
memory usage: 48.0+ bytes


In [15]:
chi2, p, degf, expected = stats.chi2_contingency(df)

In [16]:
chi2, p, degf, expected

(36.65264142122487,
 1.4116760526193828e-09,
 1,
 array([[34.5, 34.5],
        [15.5, 15.5]]))

In [17]:
print('Observed\n')
print(df.values)
print('---\nExpected\n')
print(expected.astype(int))
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[49 20]
 [ 1 30]]
---
Expected

[[34 34]
 [15 15]]
---

chi^2 = 36.6526
p     = 0.0000


In [ ]:
# here is a cleaner version...
index = ["Uses a Macbook", "Doesn't Use a Macbook"]
observed1 = pd.DataFrame({'Codeup_Student':[49,1], 'Not'})

2. Choose another 2 categorical variables from the mpg dataset and perform a 
c
h
i
2
 contingency table test with them. Be sure to state your null and alternative hypotheses.

In [41]:
# loading mpg DataFrame
mpg_df = data('mpg')
mpg_df.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [42]:
# what's it look like
mpg_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 234 entries, 1 to 234
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   manufacturer  234 non-null    object 
 1   model         234 non-null    object 
 2   displ         234 non-null    float64
 3   year          234 non-null    int64  
 4   cyl           234 non-null    int64  
 5   trans         234 non-null    object 
 6   drv           234 non-null    object 
 7   cty           234 non-null    int64  
 8   hwy           234 non-null    int64  
 9   fl            234 non-null    object 
 10  class         234 non-null    object 
dtypes: float64(1), int64(4), object(6)
memory usage: 21.9+ KB


In [43]:
mpg_df.nunique()

manufacturer    15
model           38
displ           35
year             2
cyl              4
trans           10
drv              3
cty             21
hwy             27
fl               5
class            7
dtype: int64

In [44]:
mpg_df['cyl'].value_counts()

4    81
6    79
8    70
5     4
Name: cyl, dtype: int64

In [45]:
mpg_df['fl'].value_counts()

r    168
p     52
e      8
d      5
c      1
Name: fl, dtype: int64

In [46]:
observed2 = pd.crosstab(mpg_df.cyl, mpg_df.fl)
observed2

fl   c  d  e   p   r
cyl                 
4    1  3  0  22  55
5    0  0  0   0   4
6    0  1  1  17  60
8    0  1  7  13  49

In [47]:
chi2, p, degf, expected = stats.chi2_contingency(observed2)

In [48]:
print('Observed\n')
print(observed2.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[ 1  3  0 22 55]
 [ 0  0  0  0  4]
 [ 0  1  1 17 60]
 [ 0  1  7 13 49]]
---
Expected

[[3.46153846e-01 1.73076923e+00 2.76923077e+00 1.80000000e+01
  5.81538462e+01]
 [1.70940171e-02 8.54700855e-02 1.36752137e-01 8.88888889e-01
  2.87179487e+00]
 [3.37606838e-01 1.68803419e+00 2.70085470e+00 1.75555556e+01
  5.67179487e+01]
 [2.99145299e-01 1.49572650e+00 2.39316239e+00 1.55555556e+01
  5.02564103e+01]]
---

chi^2 = 19.2459
p     = 0.0828


3. Use the data from the employees database to answer these questions:

In [53]:
query5 = '''SELECT employees.gender, departments.dept_name
FROM employees
JOIN dept_emp on dept_emp.emp_no = employees.emp_no
AND to_date > CURDATE()
JOIN departments ON dept_emp.dept_no = departments.dept_no
'''

In [54]:
dept_gender = pd.read_sql(query5, url)
dept_gender

gender         dept_name
0           M  Customer Service
1           F  Customer Service
2           M  Customer Service
3           F  Customer Service
4           F  Customer Service
...       ...               ...
240119      F             Sales
240120      M             Sales
240121      M             Sales
240122      F             Sales
240123      F             Sales

[240124 rows x 2 columns]

In [55]:
dept_gender = dept_gender[(dept_gender.dept_name == 'Sales') | (dept_gender.dept_name == 'Marketing')]

In [56]:
observed5 = pd.crosstab(dept_gender.gender, dept_gender.dept_name)
observed5

dept_name  Marketing  Sales
gender                     
F               5864  14999
M               8978  22702

In [57]:
chi2, p, degf, expected = stats.chi2_contingency(observed5)

In [58]:
print('Observed\n')
print(observed5.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[ 5864 14999]
 [ 8978 22702]]
---
Expected

[[ 5893.2426013 14969.7573987]
 [ 8948.7573987 22731.2426013]]
---

chi^2 = 0.3240
p     = 0.5692


3a. Is an employee's gender independent of whether an employee works in sales or marketing? (only look at current employees)

In [49]:
# lets look at current employees
# and then get counts of Male / Female


3b. Is an employee's gender independent of whether or not they are or have been a manager?

In [90]:
query7 = '''
SELECT employees.emp_no, employees.gender, dept_manager.dept_no
FROM employees
LEFT JOIN dept_manager AS dept_manager ON employees.emp_no = dept_manager.emp_no'''

In [91]:
mgr_gender = pd.read_sql(query7, url)

In [92]:
mgr_gender

emp_no gender dept_no
0        10001      M    None
1        10002      F    None
2        10003      M    None
3        10004      M    None
4        10005      M    None
...        ...    ...     ...
300019  499995      F    None
300020  499996      M    None
300021  499997      M    None
300022  499998      M    None
300023  499999      M    None

[300024 rows x 3 columns]

In [93]:
mgr_gender = mgr_gender.fillna(0)

In [94]:
mgr_gender = mgr_gender.rename(columns={'dept_no': 'manager'})

In [95]:
mgr_gender

emp_no gender manager
0        10001      M       0
1        10002      F       0
2        10003      M       0
3        10004      M       0
4        10005      M       0
...        ...    ...     ...
300019  499995      F       0
300020  499996      M       0
300021  499997      M       0
300022  499998      M       0
300023  499999      M       0

[300024 rows x 3 columns]

In [98]:
mgr_gender['manager'] = mgr_gender['manager'].apply(lambda x: x if x == 0 else 1)

In [99]:
mgr_gender['manager'].value_counts()

0    300000
1        24
Name: manager, dtype: int64

In [100]:
observed7 = pd.crosstab(mgr_gender['gender'], mgr_gender['manager'])

In [101]:
observed7

manager       0   1
gender             
F        120038  13
M        179962  11

In [102]:
chi2, p, degf, expected = stats.chi2_contingency(observed7)

In [105]:
print('Observed\n')
print(observed7.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[120038     13]
 [179962     11]]
---
Expected

[[1.20041397e+05 9.60331174e+00]
 [1.79958603e+05 1.43966883e+01]]
---

chi^2 = 1.4567
p     = 0.2275


In [75]:
# looking at all employees gender
gender_breakdown = pd.Series(employees_df.gender.value_counts())

In [69]:
gender_breakdown

M    179973
F    120051
Name: gender, dtype: int64