# Simulation

In this lesson, we will work through several examples of using random numbers to simulate real-world scenarios.

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

# curriculum example visualizations
# import viz
np.random.seed(1349)

### How will we utilize Python to obtain probabilities?

We will utilize Monte Carlo simulations.

A Monte Carlo simulation is a means to recreate potential events and empirically take the results of simiulated trials to obtain a reasonably precise estimate of a desired probability.

What does this mean for us here?

In [2]:
# Let's take a hypothetical base probability. 
# What is the probability of rolling a one (1) on a single, standard, fair six-sided die?


In [3]:
# Potential outcomes of a die roll:
possible_outcomes = [1,2,3,4,5,6]

In [4]:
# options that equal 1: just 1, literally one

In [5]:
ideal_roll = 1

In [6]:
theoretical_prob = ideal_roll / len(possible_outcomes)
theoretical_prob

0.16666666666666666

In [7]:
# Now how would we do this with a simulation?


In [8]:
# We will do it utilizing a large number of trials, that we calculate.

In [9]:
# Allow us to examine the same problem: Probability of rolling a 1 on a fair six-sided die.

In [10]:
# First, we will set a value for the number of trials that we want to conduct.
# We have the power of computation at our finger tips, so let's shoot for something like one million.

num_trials = 10 ** 7


In [11]:
# We have one die roll for each trial, which is our event, that we call a single simulation
n_dice =1

In [12]:
# We will do a single simulation one million times, with each simulation being a die roll.

In [13]:
rolls = np.random.choice(possible_outcomes, num_trials*n_dice).reshape(num_trials, n_dice)

In [14]:
# let's make our simulations!

In [15]:
type(rolls)

numpy.ndarray

In [16]:
(rolls == 1).mean()

0.1666723

## Generating Random Numbers with Numpy

The `numpy.random` module provides a number of functions for generating random numbers.

- `np.random.choice`: selects random options from a list
- `np.random.uniform`: generates numbers between a given lower and upper bound
- `np.random.random`: generates numbers between 0 and 1
- `np.random.randn`: generates numbers from the standard normal distribution
- `np.random.normal`: generates numbers from a normal distribution with a specified mean and standard deviation

## Example Problems

### Carnival Dice Rolls

> You are at a carnival and come across a person in a booth offering you a game
> of "chance" (as people in booths at carnivals tend to do).

> You pay 5 dollars and roll 3 dice. If the sum of the dice rolls is greater
> than 12, you get 15 dollars. If it's less than or equal to 12, you get
> nothing.

> Assuming the dice are fair, should you play this game? How would this change
> if the winning condition was a sum greater than *or equal to* 12?

To simulate this problem, we'll write the python code to simulate the scenario described above, then repeat it a large amount of times.

One way we can keep track of all the simulations is to use a 2-dimensional matrix. We can create a matrix where each row represents one "trial". Each row will have 3 columns, representing the 3 dice rolls.

In [17]:
n_trials = nrows = 10_000
n_dice = ncols = 3

rolls = np.random.choice(possible_outcomes, n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[3, 2, 1],
       [3, 6, 2],
       [3, 3, 5],
       ...,
       [1, 1, 4],
       [6, 6, 2],
       [5, 4, 3]])

Here we used the `choice` function to randomly select an element out of the list of the number 1-6, effectively simulating a dice roll. The second argument supplied to `choice` is the total number of dice to roll. Once we have generated all the dice rolls, we use the `.reshape` method to create our matrix with 3 columns and 10,000 rows.

Now that we have all of the simulated dice rolls, we want to get the sum of the dice rolls for each trial. To do this, we can use the `.sum` function and specify that we want the sum of every row (as opposed to the sum of all the numbers, or the sum by column) with the `axis` key word argument.

In [18]:
sums_by_trial = rolls.sum(axis=1)
sums_by_trial

array([ 6, 11, 11, ...,  6, 14, 12])

Let's pause here for a minute and visualize the data we have:

In [19]:
viz.simulation_example1(sums_by_trial)

NameError: name 'viz' is not defined

The area shaded in lightblue represents our chance of winning, that is, the number of times that the sum of 3 dice rolls is greater than 12.

We can now convert each value in our array to a boolean value indicating whether or not we won:

In [20]:
wins = sums_by_trial > 12

To calculate an overall win rate, we can treat each win as a `1` and each loss as `0`, then take the average of the array:

In [21]:
win_rate = wins.mean()

In [22]:
win_rate

0.2586

Now that we know our win rate, we can calculate the expected profit:

In [23]:
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit

-1.121

So we would expect, based on our simulations, on average, to lose a little over a dollar everytime we play this game.

To answer the last part of the question, we can recalculate our win rate based on the sums being greater than or equal to 12:

In [24]:
wins = sums_by_trial >= 12
win_rate = wins.mean()
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit

0.5889999999999995

If our win condition changes to the sum being greater than or equal to 12, then, based on our simulations, on average, we expect to win about 58 cents.

## Mini Exercise:

What is the probability of rolling "snake eyes" on a roll of two (fair) dice?

In [25]:
n_trials = n_rows = 10_000
n_dice = n_cols = 2

rolls = np.random.choice(possible_outcomes, n_trials * n_dice).reshape(n_rows, n_cols)
rolls

array([[6, 6],
       [4, 3],
       [2, 2],
       ...,
       [4, 6],
       [2, 5],
       [2, 2]])

In [26]:
sums_by_trial = rolls.sum(axis=1)
sums_by_trial

array([12,  7,  4, ..., 10,  7,  4])

In [27]:
wins = sums_by_trial == 2
wins

array([False, False, False, ..., False, False, False])

In [28]:
win_rate = wins.mean()
win_rate

0.0271

### No Rest or Relaxation

> There's a 30% chance my son takes a nap on any given weekend day. What is the chance that he takes a nap at least one day this weekend? What is the probability that he doesn't nap at all?

Let's first do a little bit of setup:

In [29]:
p_nap = 0.3
ndays = n_cols = 2
n_simulated_weekends = n_rows = 10_000

To simulate the results from many weekends, we'll create a 2 x 10,000 matrix, with 2 being the number of days in a weekend and 10,000 being the number of simulations we want to run.

To determine whether or not a nap is taken on a given day, we'll generate a random number between 0 and 1, and say that it is a nap if it is less than our probability of taking a nap.

In [30]:
naps = np.random.random((n_rows, n_cols))

In [31]:
naps[:10]

array([[0.18524057, 0.29228782],
       [0.64109676, 0.98283055],
       [0.64218136, 0.6191205 ],
       [0.36268078, 0.54111617],
       [0.99423743, 0.92867078],
       [0.67358305, 0.62189048],
       [0.00721732, 0.58358248],
       [0.94611047, 0.61110141],
       [0.67978087, 0.8339732 ],
       [0.01857456, 0.76816557]])

In [32]:
naps = naps < p_nap

In [33]:
naps

array([[ True,  True],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False,  True],
       [ True,  True]])

Now that we have each day as either true or false, we can take the sum of each row to find the total number of naps for the weekend. When we sum an array of boolean values, numpy will treat `True` as 1 and `False` as 0.

In [34]:
naps.sum(axis=1)

array([2, 0, 0, ..., 0, 1, 2])

Now we have the results of our simulation, an array where each number in the array represents how many naps were taken in a two day weekend.

In [35]:
viz.simulation_example2(naps)

NameError: name 'viz' is not defined

We can use this to answer our original questions, what is the probability that at least one nap is taken?

In [36]:
(naps.sum(axis=1) > 0).mean()

0.5083

What is the probability no naps are taken?

In [37]:
(naps.sum(axis=1) == 0).mean()

0.4917

In [38]:
(naps.sum(axis=1) > 1).mean()

0.0965

## Mini Exercise:

There are ten options in a blind-box style collectable, but you are only likely to get the one you want the most at a probability of one out of every twenty boxes because its a little rarer.

What is the probability of getting your desired collectable if you buy three blindbox toys?

In [39]:
p_fav = 0.05
nplays = n_cols = 3
n_trials = n_rows = 10_000

In [40]:
tests = np.random.random((n_rows, n_cols))
tests

array([[0.46190398, 0.59071453, 0.88420398],
       [0.76071154, 0.11294317, 0.85745105],
       [0.3217642 , 0.30661593, 0.90808991],
       ...,
       [0.2046499 , 0.55091891, 0.70115111],
       [0.25669068, 0.1844005 , 0.9081634 ],
       [0.55108994, 0.62560593, 0.63305804]])

In [41]:
success = tests < p_fav
success

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       ...,
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [42]:
(success.sum(axis=1) > 0).mean()

0.1382

### One With Dataframes

Let's take a look at one more problem:

> What is the probability of getting at least one 3 in 3 dice rolls?

To simulate this, we'll use a similar strategy to how we modeled the dice rolls in the previous example, but this time, we'll store the results in a pandas dataframe so that we can apply a lambda function that will check to see if one of the rolls was a 3.

In [43]:
n_trials = nrows = 10 ** 6
n_dice_rolled = ncols = 3

rolls = np.random.choice(possible_outcomes, n_trials * n_dice_rolled).reshape(nrows, ncols)

In [44]:
pd.DataFrame(rolls).apply(lambda row: 3 in row.values, axis=1)

0         False
1          True
2         False
3          True
4         False
          ...  
999995    False
999996     True
999997    False
999998    False
999999     True
Length: 1000000, dtype: bool

In [45]:
pd.DataFrame(rolls).apply(lambda row: 3 in row.values, axis=1).mean()

0.421527

Let's break down what's going on here:

1. First we assign values for the number of rows and columns we are going to use
1. Next we create the `rolls` variable that holds a 3 x 10,000 matrix where each element is a randomly chosen number from 1 to 6
1. Lastly we create a dataframe from the rolls
    1. `pd.DataFrame(rolls)` converts our 2d numpy matrix to a pandas DataFrame
    1. `.apply(...` applies a function to each **row** in our dataframe, because we specified `axis=1`, the function will be called with each row as it's argument. The body of the function checks to see if the value `3` is in the values of the row, and will return either `True` or `False`
    1. `.mean()` takes our resulting series of boolean values, and treats `True` as 1 and `False` as 0, to give us the average rate of `True`s, in this case, the simulated probability of getting a 3 in 3 dice rolls.

## Mini Exercise:

Recreate the blindbox problem utilizing the above strategy!


In [46]:
p_fav = 0.05
nplays = n_cols = 3
n_trials = n_rows = 10_000

In [47]:
tests = np.random.random((n_rows, n_cols))
tests

array([[0.90388223, 0.63535659, 0.42247723],
       [0.91952571, 0.61142113, 0.41237677],
       [0.09147618, 0.15018211, 0.23808321],
       ...,
       [0.31770538, 0.79834288, 0.04716317],
       [0.20084301, 0.01538891, 0.58192146],
       [0.40327877, 0.74174039, 0.38113355]])

In [48]:
pd.DataFrame(tests).apply(lambda x: x<p_fav, axis=1).mean()

0    0.0498
1    0.0519
2    0.0511
dtype: float64

In [49]:
# diferent method...
n_rows = 10_000
n_cols = 3
outcomes = [1,2,3,4,5,6,7,8,9,10]
prob_win = 0.05
prob_others = (1-prob_win)/9

In [50]:
data = np.random.choice(outcomes, n_rows * n_cols, p=[prob_win, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others]).reshape(n_rows, n_cols)

In [51]:
data[:5]

array([[2, 4, 7],
       [6, 6, 9],
       [3, 7, 7],
       [7, 8, 4],
       [4, 2, 1]])

In [52]:
pd.DataFrame(data).apply(lambda row: 1 in row.values, axis=1).mean()

0.1395

## Exercises

Within your `codeup-data-science directory`, create a directory named `statistics-exercises`. This will be where you do your work for this module. Create a repository on GitHub with the same name, and link your local repository to GitHub.

Do your work for this exercise in either a python file named `simulation.py` or a jupyter notebook named `simulation.ipynb`.

1. How likely is it that you roll doubles when rolling two dice?

In [53]:
# first I am going to solve the problem mathematically, so I have a baseline and can get my bearings...
(1/6)*(1/6)*6

0.16666666666666666

In [54]:
# now programmatically
n_trials = r_rows = 10_000
n_dice = n_cols = 2
possible_outcomes = [1,2,3,4,5,6]

data = np.random.choice(possible_outcomes, n_rows * n_cols).reshape(n_rows, n_cols)
data[:5]

array([[1, 1],
       [1, 2],
       [4, 1],
       [3, 4],
       [5, 5]])

In [55]:
pd.DataFrame(data).apply(lambda x: x[0]==x[1] in x.values, axis=1).mean()

0.1682

In [56]:
# another way to do this would be to do the snake eyes method, and then multiply by 6
# since each set of doubles has an identical chance of occurring
n_trials = n_rows = 10_000
n_dice = n_cols = 2

rolls = np.random.choice(possible_outcomes, n_trials * n_dice).reshape(n_rows, n_cols)

sums_by_trial = rolls.sum(axis=1)

wins = sums_by_trial == 2

win_rate = wins.mean()

doubles = win_rate*6
doubles


0.14579999999999999

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 

In [57]:
# first let's solve this mathematically, to make sure our work in the future is correct
#  you can get exactly 3 heads



In [58]:
n_trials = n_rows = 10_000
n_coins = n_cols = 8

heads = 1
tails =0

outcomes = [heads, tails]

flips = np.random.choice(outcomes, n_coins * n_trials).reshape(n_trials, n_coins)
flips



array([[1, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 1, 0, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 1, 1],
       [0, 1, 0, ..., 1, 0, 0]])

In [59]:
sum_by_flips = flips.sum(axis=1)
sum_by_flips

array([5, 5, 4, ..., 6, 4, 3])

In [60]:
exactly_three = (sum_by_flips==3).mean()
exactly_three

0.2205

What is the probability of getting more than 3 heads?

In [61]:
n_trials = n_rows = 10_000
n_coins = n_cols = 8

heads = 1
tails = 0

outcomes = [heads, tails]

flips = np.random.choice(outcomes, n_coins * n_trials).reshape(n_trials, n_coins)
flips

array([[1, 0, 1, ..., 1, 0, 0],
       [1, 1, 1, ..., 0, 1, 0],
       [1, 0, 1, ..., 1, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 1, 0, 1]])

In [62]:
sum_by_flips = flips.sum(axis=1)
sum_by_flips

array([3, 6, 6, ..., 3, 4, 3])

In [63]:
more_than_three = (sum_by_flips>3).mean()
more_than_three

0.6378

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [64]:
# let's assume each cohort has the same number of students

n_trials = n_rows = 10_000
n_draw = n_cols = 2

outcomes = [3,1]

prob_wb = 0.75
prob_ds = 1-prob_wb

data = np.random.choice(outcomes, n_rows * n_cols, p=[prob_wb, prob_ds]).reshape(n_rows, n_cols)
data

array([[1, 3],
       [3, 3],
       [3, 3],
       ...,
       [3, 3],
       [1, 1],
       [3, 3]])

In [65]:
sum_it_up = data.sum(axis=1)
sum_it_up

array([4, 6, 6, ..., 6, 2, 6])

In [66]:
double_ds = (sum_it_up == 2).mean()
double_ds

0.0614

4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [67]:
n_trials = n_rows = 10_000
n_days = n_cols = 5

testing = np.random.normal(3, 1.5, size =(10_000,5))
testing

array([[3.17317878, 4.34320172, 1.79818967, 3.72628749, 3.32456431],
       [2.53269154, 3.59368194, 2.91677492, 2.88253772, 1.24946686],
       [2.19351905, 2.51422637, 5.14692721, 3.79159344, 2.79119592],
       ...,
       [4.96245737, 6.13732849, 2.46683366, 2.04411034, 3.62661697],
       [0.56379143, 1.19838439, 3.00140138, 3.03792432, 3.25052925],
       [2.70914035, 1.31597063, 4.87940622, 3.38321013, 1.8148605 ]])

In [68]:
testing_sums = testing.sum(axis=1)
testing_sums

array([16.36542197, 13.17515299, 16.43746198, ..., 19.23734683,
       11.05203077, 14.10258783])

In [69]:
yes_poptarts = (testing_sums < 17).mean()
yes_poptarts

0.725

5. Compare Heights

    - Men have an average height of 178 cm and standard deviation of 8cm.
    - Women have a mean of 170, sd = 6cm.
    - If a man and woman are chosen at random, P(woman taller than man)?

In [70]:
n_rows = 10_000
n_cols = 2

# create normal distribution of Men's height
men_dist = np.random.normal(178, 8, size=(10_000,1))
# create normal distribution of Women's height
women_dist = np.random.normal(170, 6, size=(10_000,1))

both_dist = np.column_stack((men_dist, women_dist))
both_dist


array([[164.85567623, 162.55116268],
       [178.50451268, 156.45432892],
       [157.41566642, 168.07189581],
       ...,
       [181.32316483, 166.18913605],
       [177.71824542, 173.07697128],
       [163.36663411, 161.98614291]])

In [71]:
men_women = np.subtract(men_dist, women_dist)
men_women

array([[  2.30451355],
       [ 22.05018376],
       [-10.65622938],
       ...,
       [ 15.13402878],
       [  4.64127414],
       [  1.38049119]])

In [72]:
women_men = (men_women < 0).mean()
women_men

0.211

6. When installing anaconda on a student's computer, there's a 1 in 250 chance
   that the download is corrupted and the installation fails. What are the odds
   that after having 50 students download anaconda, no one has an installation
   issue?  100 students?

    What is the probability that we observe an installation issue within the first
    150 students that download anaconda?

    How likely is it that 450 students all download anaconda without an issue?

In [73]:
# fail = 0
# succeed = 1
n_trials = n_rows = 10_000
n_students = n_cols = 50
fail_prob = (1/250)
no_fail = 1-fail_prob
outcomes = [0,1]

fifty_test = np.random.choice(outcomes, n_cols * n_rows, p = [fail_prob, no_fail]).reshape(n_rows, n_cols)
fifty_test



array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [74]:
fifty_totals = fifty_test.sum(axis=1)
fifty_totals

array([50, 50, 50, ..., 50, 49, 50])

In [75]:
fifty_fail = (fifty_totals<50).mean()
fifty_fail

0.1767

In [76]:
fifty_success = 1-fifty_fail
fifty_success

0.8233

In [77]:
# 100 students
# fail = 0
# succeed = 1
n_trials = n_rows = 10_000
n_students = n_cols = 100
fail_prob = (1/250)
no_fail = 1-fail_prob
outcomes = [0,1]

hundred_test = np.random.choice(outcomes, n_cols * n_rows, p = [fail_prob, no_fail]).reshape(n_rows, n_cols)
hundred_test

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [78]:
hundred_totals = hundred_test.sum(axis=1)
hundred_totals

array([100, 100, 100, ..., 100, 100, 100])

In [79]:
hundred_fail = (hundred_totals<100).mean()
hundred_fail

0.3296

In [80]:
hundred_success = 1-hundred_fail
hundred_success

0.6704

In [81]:
# 150 students
# fail = 0
# succeed = 1
n_trials = n_rows = 10_000
n_students = n_cols = 150
fail_prob = (1/250)
no_fail = 1-fail_prob
outcomes = [0,1]

hundred_fifty_test = np.random.choice(outcomes, n_cols * n_rows, p = [fail_prob, no_fail]).reshape(n_rows, n_cols)
hundred_fifty_test


array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [82]:
hundred_fifty_totals = hundred_fifty_test.sum(axis=1)
hundred_fifty_totals

array([148, 150, 150, ..., 149, 147, 149])

In [83]:
hundred_fifty_fail = (hundred_fifty_totals<150).mean()
hundred_fifty_fail

0.4586

In [84]:
hundred_fifty_success = 1-hundred_fifty_fail
hundred_fifty_success

0.5414

In [85]:
# 450 students
# fail = 0
# succeed = 1
n_trials = n_rows = 10_000
n_students = n_cols = 450
fail_prob = (1/250)
no_fail = 1-fail_prob
outcomes = [0,1]

four_fifty_test = np.random.choice(outcomes, n_cols * n_rows, p = [fail_prob, no_fail]).reshape(n_rows, n_cols)
four_fifty_test

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [86]:
four_fifty_totals = four_fifty_test.sum(axis=1)
four_fifty_totals

array([450, 449, 447, ..., 448, 449, 446])

In [87]:
four_fifty_fail = (four_fifty_totals<450).mean()
four_fifty_fail

0.8352

In [88]:
four_fifty_success = 1-four_fifty_fail
four_fifty_success

0.16479999999999995

7. There's a 70% chance on any given day that there will be at least one food
   truck at Travis Park. However, you haven't seen a food truck there in 3 days.
   How unlikely is this?

    How likely is it that a food truck will show up sometime this week?

In [89]:
no_truck = 0
truck = 1

n_trials = n_rows = 10_000
n_days = n_cols = 3
outcomes = [0,1]
truck_prob = 0.7
no_truck_prob = 0.3

three_day_test = np.random.choice(outcomes, n_cols * n_rows, p=[no_truck_prob, truck_prob]).reshape(n_rows, n_cols)
three_day_test


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 0],
       ...,
       [1, 1, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [90]:
three_day_sum = three_day_test.sum(axis=1)
three_day_sum

array([3, 3, 2, ..., 3, 2, 2])

In [91]:
bad_luck = (three_day_sum==0).mean()
bad_luck

0.0293

In [92]:
# how likely is it that a truck will show up this week, 
# given that 3 days in, there has not been a truck, 
# what are the chances of a truck showing up at least once in the next 4 days?

no_truck = 0
truck = 1

n_trials = n_rows = 10_000
n_days = n_cols = 4
outcomes = [0,1]
truck_prob = 0.7
no_truck_prob = 0.3

four_day_test = np.random.choice(outcomes, n_cols * n_rows, p=[no_truck_prob, truck_prob]).reshape(n_rows, n_cols)
four_day_test


array([[1, 1, 1, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 0],
       ...,
       [0, 1, 0, 0],
       [1, 1, 0, 1],
       [1, 0, 0, 1]])

In [93]:
four_day_sum = four_day_test.sum(axis=1)
four_day_sum

array([4, 3, 3, ..., 1, 3, 2])

In [94]:
good_luck = (four_day_sum > 0).mean()
good_luck

0.9904

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [95]:
# first, we have to assume that each date has an equal chance of being someone's birthdate

b_days = np.arange(1,366)

n_trials = n_rows = 10_000
n_people = n_cols = 23

first_test = np.random.choice(b_days, n_cols * n_rows).reshape(n_rows, n_cols)
first_test

array([[326, 306, 170, ...,  11,  69, 169],
       [314, 290, 332, ..., 135, 289, 353],
       [143,  94, 198, ..., 172, 354,  68],
       ...,
       [215,  34, 186, ...,  22,  14,   9],
       [182, 168,  60, ..., 115, 246, 290],
       [151, 282,  46, ...,  41, 286, 264]])

In [96]:
second_test = pd.DataFrame(first_test)
second_test

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0     326  306  170  340  193  217  203  307  292  225  ...  221   24   39   
1     314  290  332   69  112  286  100  344  270  137  ...   93   93   89   
2     143   94  198   52  264  277  193  274   10  287  ...  273   48   74   
3     146  344   87  252  186   14   14  345  302  250  ...  337  351  214   
4      91   45   74  254  180   64  199  364  244  268  ...   26  312  351   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  242  293  187  194   11  153  183  314   27   86  ...  171   14   12   
9996  157  162  365  135  166  113  104   47  195  271  ...   78  184   34   
9997  215   34  186  115  199  236  219   70   23  337  ...  316   78  221   
9998  182  168   60   89   53  320   50  284  235  281  ...  196  287  225   
9999  151  282   46  216  266   71  315  198  235    5  ...   12   74   41   

       16   17   18   19   20   21   22  
0     116  191  364   32   11   69  169  
1     194  365  307   95  135  289  353  
2      78  266   70   89  172  354   68  
3     357  268  110  347  356  198  105  
4     228  250   57   34    6  309  210  
...   ...  ...  ...  ...  ...  ...  ...  
9995   32  321  148  340  267  226  261  
9996   86   69  129  206  290  344  318  
9997  121  257   29  141   22   14    9  
9998  299  199  225  202  115  246  290  
9999  216  320  296  256   41  286  264  

[10000 rows x 23 columns]

In [97]:
third_test = second_test.nunique(axis=1)
third_test

0       23
1       22
2       23
3       22
4       22
        ..
9995    23
9996    22
9997    23
9998    22
9999    21
Length: 10000, dtype: int64

In [98]:
fourth_test = (third_test < 23).mean()
fourth_test

0.5041

In [99]:
# what if it's only 20 people

b_days = np.arange(1,366)

n_trials = n_rows = 10_000
n_people = n_cols = 20

twenty_test = np.random.choice(b_days, n_cols * n_rows).reshape(n_rows, n_cols)
twenty_test

array([[261, 357,  42, ...,  61, 205, 172],
       [127, 168, 148, ..., 345, 128, 266],
       [329, 246, 310, ..., 118,  79,   4],
       ...,
       [356,  23, 139, ...,  46, 160,  97],
       [ 47, 297,  13, ..., 130, 319,  16],
       [311, 325, 265, ..., 108,  16,  93]])

In [100]:
second_twenty = pd.DataFrame(twenty_test)
second_twenty

0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
0     261  357   42  157  113  245  283  191  169  133  111   73   98  333   
1     127  168  148  131  363  343  135  165    6  120  100   50  335  343   
2     329  246  310   91  210  166  319  259  361   14  333  132    5  135   
3     143  120  180  165  322  186  201  361  261  149  217  242  349   74   
4      77  172  358  267  236  344  296   81  356  251  120  169  315  253   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  320  192  184  270  136   73   28  107  212  179  105  358   57  144   
9996  148  147   54  316  169   23  321   34   13  173  209   25   12  183   
9997  356   23  139  143   83  208  200  307  264  151  132  211    2  109   
9998   47  297   13  333  161  223  336  247  276  323   81  345   42  247   
9999  311  325  265  105  128  224  314  176  294  355   88   11  294  147   

       14   15   16   17   18   19  
0     108   24  207   61  205  172  
1     320  206  190  345  128  266  
2     338  131  251  118   79    4  
3     295  151   36   74  365  217  
4      38  292  225  304  197  273  
...   ...  ...  ...  ...  ...  ...  
9995   72   67  266   97   45  107  
9996  171  229  280  120  359  234  
9997  251  292  249   46  160   97  
9998  199  235  257  130  319   16  
9999    1  213  187  108   16   93  

[10000 rows x 20 columns]

In [101]:
third_twenty = second_twenty.nunique(axis=1)
third_twenty

0       20
1       19
2       20
3       18
4       20
        ..
9995    19
9996    20
9997    20
9998    19
9999    19
Length: 10000, dtype: int64

In [102]:
fourth_twenty = (third_twenty < 20).mean()
fourth_twenty

0.4129

In [103]:
# what about 40 people?
b_days = np.arange(1,366)

n_trials = n_rows = 10_000
n_people = n_cols = 40

forty_test = np.random.choice(b_days, n_cols * n_rows).reshape(n_rows, n_cols)
forty_test

array([[281,  43, 103, ..., 284, 190,   6],
       [334,  94,  16, ..., 339, 130, 314],
       [255, 362, 268, ...,  39, 253,  68],
       ...,
       [117, 350, 178, ..., 340, 275,  31],
       [185,  88,  50, ...,  45,  10,  52],
       [318, 286, 311, ..., 164,   7, 316]])

In [104]:
second_forty = pd.DataFrame(forty_test)
second_forty

0    1    2    3    4    5    6    7    8    9   ...   30   31   32  \
0     281   43  103  157  217  320   37  317   84  266  ...  275  173  190   
1     334   94   16   18  193   32  250  218  275  305  ...  129   28  325   
2     255  362  268  190  319   14  183  276  357  100  ...  143  256  231   
3     302  257  353  356   58  111  268   66  247   99  ...  311  143  201   
4     198  290  102   85   96  319  102  278  343   76  ...    9  216  286   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  251   93   25   45  214  291   67   95  265  324  ...  104  141  286   
9996  346  182  203  260  319  124  162  231  211  208  ...  335  246   79   
9997  117  350  178   34  146  201   68    6  312   34  ...   80  287  265   
9998  185   88   50   41  351  198  129  325  320  345  ...   71  327  316   
9999  318  286  311   70  321  353  250  325  273   15  ...   68  356  200   

       33   34   35   36   37   38   39  
0     346  232   73   85  284  190    6  
1     253   49  262  351  339  130  314  
2     165   42  259  176   39  253   68  
3     319   43   83    8   99   75  288  
4     192   67  218   35   93  257  276  
...   ...  ...  ...  ...  ...  ...  ...  
9995    9  317   59  119  207    1  166  
9996  352  215  350  165  117  168  210  
9997   40   17  241  362  340  275   31  
9998  343  292  350  285   45   10   52  
9999  301   25   13  115  164    7  316  

[10000 rows x 40 columns]

In [105]:
third_forty = second_forty.nunique(axis=1)
third_forty

0       38
1       37
2       38
3       36
4       39
        ..
9995    40
9996    39
9997    36
9998    38
9999    39
Length: 10000, dtype: int64

In [106]:
fourth_forty = (third_forty < 40).mean()
fourth_forty

0.8968

#### Bonus Exercises
- [Mage Duel](https://gist.github.com/ryanorsinger/2996446f02c1bf30fcb3f8fdb88bd51d)
- [Chuck a Luck](https://gist.github.com/ryanorsinger/eac1d7b7e978f90b8390bdc056312123)